version: "3"
services:
    meilisearch:
        image: getmeili/meilisearch:v0.28
        restart: always
        volumes:
            - ./meili_data:/meili_data
        ports:
            - "7700:7700"
        environment:
            - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
        container_name: meilisearch
        expose:
            - "7700"
    injecter:
        container_name: data_injecter
        build: .
        depends_on:
            - meilisearch
        volumes:
            - ./csv:/csv
            - ./scripts:/scripts
        environment:
            - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
            - MEILI_SERVER=${MEILI_SERVER}
